export const ERROR_CODES = {
  // --- Auth ---
  AUTH_INVALID_CREDENTIALS:         'AUTH_INVALID_CREDENTIALS',
  AUTH_TOKEN_EXPIRED:               'AUTH_TOKEN_EXPIRED',
  AUTH_TOKEN_INVALID:               'AUTH_TOKEN_INVALID',
  AUTH_INSUFFICIENT_PERMISSION:     'AUTH_INSUFFICIENT_PERMISSION',
  AUTH_USER_INACTIVE:               'AUTH_USER_INACTIVE',

  // --- User ---
  USER_NOT_FOUND:                   'USER_NOT_FOUND',
  STUDENT_NOT_FOUND:                'STUDENT_NOT_FOUND',
  USER_EMAIL_EXISTS:                'USER_EMAIL_EXISTS',
  USER_CODE_EXISTS:                 'USER_CODE_EXISTS',

  // --- Program ---
  PROGRAM_NOT_FOUND:                'PROGRAM_NOT_FOUND',

  // --- Class ---
  CLASS_NOT_FOUND:                  'CLASS_NOT_FOUND',
  CLASS_TEACHER_CONFLICT:           'CLASS_TEACHER_CONFLICT',
  CLASS_ROOM_CONFLICT:              'CLASS_ROOM_CONFLICT',
  CLASS_CAPACITY_EXCEEDED:          'CLASS_CAPACITY_EXCEEDED',

  // --- Enrollment ---
  ENROLLMENT_NOT_FOUND:             'ENROLLMENT_NOT_FOUND',
  ENROLLMENT_ALREADY_ACTIVE:        'ENROLLMENT_ALREADY_ACTIVE',
  ENROLLMENT_INVALID_STATUS:        'ENROLLMENT_INVALID_STATUS',
  ENROLLMENT_TRANSFER_AFTER_FREE_PERIOD: 'ENROLLMENT_TRANSFER_AFTER_FREE_PERIOD',

  SESSION_NOT_FOUND:                'SESSION_NOT_FOUND',
  ACCESS_DENIED:                    'ACCESS_DENIED',
  TRANSITION_BLOCKED:               'TRANSITION_BLOCKED',

  // --- Attendance ---
  ATTENDANCE_NOT_FOUND:             'ATTENDANCE_NOT_FOUND',
  MAKEUP_SESSION_NOT_FOUND:         'MAKEUP_SESSION_NOT_FOUND',
  ATTENDANCE_ALREADY_RECORDED:      'ATTENDANCE_ALREADY_RECORDED',
  ATTENDANCE_MAKEUP_BLOCKED:        'ATTENDANCE_MAKEUP_BLOCKED',
  ATTENDANCE_UNEXCUSED_NO_MAKEUP:   'ATTENDANCE_UNEXCUSED_NO_MAKEUP',
  MAKEUP_DATE_TOO_LATE:             'MAKEUP_DATE_TOO_LATE',

  // --- Receipt ---
  RECEIPT_ENROLLMENT_REQUIRED:      'RECEIPT_ENROLLMENT_REQUIRED',
  RECEIPT_NOT_FOUND:                'RECEIPT_NOT_FOUND',

  // --- Payroll ---
  PAYROLL_ALREADY_FINALIZED:        'PAYROLL_ALREADY_FINALIZED',
  PAYROLL_NOT_FOUND:                'PAYROLL_NOT_FOUND',

  // --- Pause Request ---
  PAUSE_REQUEST_NOT_FOUND:          'PAUSE_REQUEST_NOT_FOUND',
  PAUSE_REQUEST_ALREADY_REVIEWED:   'PAUSE_REQUEST_ALREADY_REVIEWED',

  // --- Refund ---
  REFUND_REQUEST_NOT_FOUND:         'REFUND_REQUEST_NOT_FOUND',

  // --- Generic ---
  VALIDATION_ERROR:                 'VALIDATION_ERROR',
  NOT_FOUND:                        'NOT_FOUND',
  INTERNAL_ERROR:                   'INTERNAL_ERROR',
  DUPLICATE_ERROR:                  'DUPLICATE_ERROR',
  REFERENCE_ERROR:                  'REFERENCE_ERROR',

  /** Quá nhiều request (rate limit) */
  RATE_LIMIT_EXCEEDED:              'RATE_LIMIT_EXCEEDED',

  /** Chuyển lớp: đã học ≥3 buổi */
  ENROLLMENT_TRANSFER_LOCKED:       'ENROLLMENT_TRANSFER_LOCKED',
  /** Chuyển lớp: đã hết lượt chuyển */
  ENROLLMENT_TRANSFER_LIMIT:        'ENROLLMENT_TRANSFER_LIMIT',
} as const;

export type ErrorCode = typeof ERROR_CODES[keyof typeof ERROR_CODES];
